name: Fast Forward to Release
description: 'Merge Fast Forward from Main to Release after Checks Complete'
on:
  # if: github.ref_name == github.event.repository.default_branch
  check_suite:
    types: [completed]

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Echo Event
      run: |
        jq_expr='.check_suite.pull_requests[]|select("${{ github.event.check_suite.head_branch }}"==.head.ref)|"BASE_REF=\(.base.ref)\nHEAD_REF=\(.head.sha)"'
        jq -r "${jq_expr}" <<HERE >> "${GITHUB_ENV}"
        ${{ toJSON(github.event) }}
        HERE
    - name: Checkout code into workspace directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ssh-key: ${{ inputs.SSH_PRIVATE_KEY }}
        persist-credentials: true
    - name: FF Merge
      run: |
        git checkout "${BASE_REF}"
        git merge --ff-only "${HEAD_REF}"
        git push --dry-run origin "${BASE_REF}"